# Uncomment and fill in the platforms you want to show in the
# "Sponsor this project" button on GitHub. Only include keys you use.
#
# github: [username]
# patreon: username
# open_collective: project
# ko-fi: username
# tidelift: package-manager/package-name
# custom: ["https://example.com/sponsor"]
